# Generated by Django 4.2.11 on 2024-03-18 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('statut', models.IntegerField()),
                ('dateLivraison', models.DateField()),
                ('dateDebut', models.DateField()),
                ('avancementEffectif', models.FloatField()),
                ('avancementSuppose', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('mdp', models.TextField(max_length=255)),
                ('mail', models.EmailField(max_length=254)),
                ('estResponsable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priorite', models.IntegerField()),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
                ('statut', models.IntegerField()),
                ('rapportAvancement', models.TextField(blank=True)),
                ('avancement', models.FloatField()),
                ('executant', models.ManyToManyField(to='projectmanagement.utilisateur')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.projet')),
                ('tacheParent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.tache')),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.utilisateur'),
        ),
    ]
