# Generated by Django 4.2.11 on 2024-03-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='estTest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tache',
            name='estTest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='estTest',
            field=models.BooleanField(default=False),
        ),
    ]
