# Generated by Django 4.2.11 on 2024-03-24 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0002_projet_esttest_tache_esttest_utilisateur_esttest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='avancementEffectif',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='avancementSuppose',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='avancement',
        ),
        migrations.AddField(
            model_name='projet',
            name='statutVerbose',
            field=models.CharField(default='en pause', max_length=40),
        ),
        migrations.AlterField(
            model_name='projet',
            name='dateDebut',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='projet',
            name='dateLivraison',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.IntegerField(default=3),
        ),
    ]
