# Generated by Django 4.2.11 on 2024-03-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0003_remove_projet_avancementeffectif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='dateDebut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='dateLivraison',
            field=models.DateField(blank=True, null=True),
        ),
    ]
