# Generated by Django 4.2.11 on 2024-04-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0004_alter_projet_datedebut_alter_projet_datelivraison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='statutVerbose',
        ),
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.IntegerField(default=0),
        ),
    ]
